//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiDaiLi1Entities : DbContext
    {
        public QuanLiDaiLi1Entities()
            : base("name=QuanLiDaiLi1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoSoDaiLi1> HoSoDaiLi1 { get; set; }
        public virtual DbSet<PhieuThuTien1> PhieuThuTien1 { get; set; }
        public virtual DbSet<PhieuXuatHang1> PhieuXuatHang1 { get; set; }
        public virtual DbSet<Quan> Quans { get; set; }
        public virtual DbSet<QuyDinh1> QuyDinh1 { get; set; }
        public virtual DbSet<UserRolee1> UserRolee1 { get; set; }
        public virtual DbSet<Userss1> Userss1 { get; set; }
    }
}
