//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLi.Model
{
    using QuanLyDaiLi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuTien1:BaseViewModel
    {
        public int Id { get; set; }
        private string _IdTenDaiLy;
        public string IdTenDaiLy { get => _IdTenDaiLy; set { _IdTenDaiLy = value; OnPropertyChanged(); } }
        private string _Address;
        public string Address { get => _Address; set { _Address = value; OnPropertyChanged(); } }
        private string _Phone;
        public string Phone { get => _Phone; set { _Phone = value; OnPropertyChanged(); } }
        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }
        private System.DateTime _NgayThuTien;
        public System.DateTime NgayThuTien { get => _NgayThuTien; set { _NgayThuTien = value; OnPropertyChanged(); } }
        private Nullable<double> _SoTienThu;
        public Nullable<double> SoTienThu { get => _SoTienThu; set { _SoTienThu = value; OnPropertyChanged(); } }

        private HoSoDaiLi1 _HoSoDaiLi1;
        public virtual HoSoDaiLi1 HoSoDaiLi1 { get => _HoSoDaiLi1; set { _HoSoDaiLi1 = value; OnPropertyChanged(); } }
    }
}
