//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLi.Model
{
    using QuanLyDaiLi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatHang1:BaseViewModel
    {
        public int Id { get; set; }
        private string _IdTenDaiLy;
        public string IdTenDaiLy { get => _IdTenDaiLy; set { _IdTenDaiLy = value; OnPropertyChanged(); } }
        private System.DateTime _NgayLapPhieu;
        public System.DateTime NgayLapPhieu { get => _NgayLapPhieu; set { _NgayLapPhieu = value; OnPropertyChanged(); } }
        private string _MatHang;
        public string MatHang { get => _MatHang; set { _MatHang = value; OnPropertyChanged(); } }
        private string _DonViTinh;
        public string DonViTinh { get => _DonViTinh; set { _DonViTinh = value; OnPropertyChanged(); } }
        private int _SoLuong;
        public int SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }
        private double _DonGia;
        public double DonGia { get => _DonGia; set { _DonGia = value; OnPropertyChanged(); } }
        private Nullable<int> _ThanhTien;
        public Nullable<int> ThanhTien { get => _ThanhTien; set { _ThanhTien = value; OnPropertyChanged(); } }
        private HoSoDaiLi1 _HoSoDaiLi1;
        public virtual HoSoDaiLi1 HoSoDaiLi1 { get => _HoSoDaiLi1; set { _HoSoDaiLi1 = value; OnPropertyChanged(); } }
    }
}
