//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLi.Model
{
    using QuanLyDaiLi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Quan:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quan()
        {
            this.HoSoDaiLi1 = new HashSet<HoSoDaiLi1>();
        }
    
        public int id { get; set; }
        private string _TenQuan;
        public string TenQuan { get=>_TenQuan; set { _TenQuan = value;OnPropertyChanged(); } }
        private int _SoDaiLi;
        public int SoDaiLi { get=>_SoDaiLi; set { _SoDaiLi = value;OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoDaiLi1> HoSoDaiLi1 { get; set; }
    }
}
