//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLi.Model
{
    using QuanLyDaiLi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh1:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyDinh1()
        {
            this.HoSoDaiLi1 = new HashSet<HoSoDaiLi1>();
        }

        public int Id { get; set; }
        private string _LoaiDaiLy;
        public string LoaiDaiLy { get => _LoaiDaiLy; set { _LoaiDaiLy = value; OnPropertyChanged(); } }
        private int _SoLuong;
        public int SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoDaiLi1> HoSoDaiLi1 { get; set; }
    }
}
